In [17]:
import pandas as pd 
df = pd.read_csv("goat.csv")
print (df)

           Date Product_Category   Price  Discount Customer_Segment  \
0    01-01-2023           Sports  932.80     35.82       Occasional
1    02-01-2023             Toys  569.48      3.60          Premium
2    03-01-2023       Home Decor  699.68      3.56          Premium
3    04-01-2023             Toys  923.27      0.61          Premium
4    05-01-2023             Toys  710.17     47.83          Premium
..          ...              ...     ...       ...              ...
995  22-09-2025          Fashion  740.06     49.06          Regular
996  23-09-2025      Electronics  517.10     28.48          Premium
997  24-09-2025      Electronics  683.43     12.98       Occasional
998  25-09-2025           Sports   51.26     21.85       Occasional
999  26-09-2025       Home Decor   93.94     29.68          Regular

     Marketing_Spend  Units_Sold
0            6780.38          32
1            6807.56          16
2            3793.91          27
3            9422.75          29
4            1756.83          17
..               ...         ...
995          1890.83          34
996          8011.66          21
997          3408.51          19
998          7335.62          26
999          4258.11          39

[1000 rows x 7 columns]

In [3]:
import pandas as pd
tuner = pd.read_csv("spotify_tracks.csv")
print (tuner)

                     track_id                                  track_name  \
0      2r0ROhr7pRN4MXDMT1fEmd                  Leo Das Entry (From "Leo")
1      4I38e6Dg52a2o2a8i5Q5PW                                AAO KILLELLE
2      59NoiRhnom3lTeRFaBzOev      Mayakiriye Sirikiriye - Orchestral EDM
3      5uUqRQd385pvLxC8JX3tXn    Scene Ah Scene Ah - Experimental EDM Mix
4      1KaBRg2xgNeCljmyxBH1mo  Gundellonaa X I Am A Disco Dancer - Mashup
...                       ...                                         ...
62312  3eHDwMQYPEziy2DWRBNoLv                        Sani - G.O.A.T Remix
62313  5hHtCqkNv5eo99OrEFFcgS                            Life of Bachelor
62314  08foF9YHgKmIgOy3xMWRZy                                     Yo Baby
62315  2wLFbVlQGKJSd9lwzwL47F                           Fast Fast Vadiley
62316  5OYxwYeFfumMTAoAdVeet3             Moonu Moonu Moonu (From "3:33")

                                             artist_name  year  popularity  \
0                                    Anirudh Ravichander  2024          59
1      Anirudh Ravichander, Pravin Mani, Vaishali Sri...  2024          47
2               Anirudh Ravichander, Anivee, Alvin Bruno  2024          35
3      Anirudh Ravichander, Bharath Sankar, Kabilan, ...  2024          24
4      Anirudh Ravichander, Benny Dayal, Leon James, ...  2024          22
...                                                  ...   ...         ...
62312  Arvind Raj, Sheezay, Music Kitchen, FSPROD Vin...  2021          30
62313  A H Kaashif, Navakkarai Naveen Prabanjam, Asal...  2021          30
62314         Rakesh Ambigapathy, Asal Kolaar, MC Vickey  2021          18
62315          Asal Kolaar, Priyadarshan Balasubramanian  2021           1
62316  Harshavardhan Rameshwar, G. V. Prakash, Dharma...  2021           1

                                             artwork_url  \
0      https://i.scdn.co/image/ab67616d0000b273ce9c65...
1      https://i.scdn.co/image/ab67616d0000b273be1b03...
2      https://i.scdn.co/image/ab67616d0000b27334a1dd...
3      https://i.scdn.co/image/ab67616d0000b27332e623...
4      https://i.scdn.co/image/ab67616d0000b2735a59b6...
...                                                  ...
62312  https://i.scdn.co/image/ab67616d0000b273819d23...
62313  https://i.scdn.co/image/ab67616d0000b2736cd651...
62314  https://i.scdn.co/image/ab67616d0000b27300da25...
62315  https://i.scdn.co/image/ab67616d0000b273e051e1...
62316  https://i.scdn.co/image/ab67616d0000b273efd671...

                                          album_name  acousticness  \
0                         Leo Das Entry (From "Leo")       0.02410
1                                       AAO KILLELLE       0.08510
2             Mayakiriye Sirikiriye (Orchestral EDM)       0.03110
3           Scene Ah Scene Ah (Experimental EDM Mix)       0.22700
4         Gundellonaa X I Am a Disco Dancer (Mashup)       0.01530
...                                              ...           ...
62312                           Sani (G.O.A.T Remix)       0.08490
62313  Bachelor (Original Motion Picture Soundtrack)       0.07880
62314                                        Yo Baby       0.00918
62315                                Arjuna Phalguna       0.10100
62316                Moonu Moonu Moonu (From "3:33")       0.18600

       danceability  duration_ms  ...   key  liveness  loudness  mode  \
0             0.753      97297.0  ...   8.0    0.1000    -5.994   0.0
1             0.780     207369.0  ...  10.0    0.0951    -5.674   0.0
2             0.457      82551.0  ...   2.0    0.0831    -8.937   0.0
3             0.718     115831.0  ...   7.0    0.1240   -11.104   1.0
4             0.689     129621.0  ...   7.0    0.3450    -9.637   1.0
...             ...          ...  ...   ...       ...       ...   ...
62312         0.877     359718.0  ...   7.0    0.1100   -11.458   1.0
62313         0.833     154364.0  ...   8.0    0.2670    -5.061   1.0
62314         0.842     234000.0  ...   7.0    0.0790    -5.855   1.0
62315         0.682     180807.0  ...   1.0    0.3200    -6.061   1.0
62316         0.817     202667.0  ...   6.0    0.3780    -7.353   0.0

       speechiness    tempo  time_signature  valence  \
0           0.1030  110.997             4.0    0.459
1           0.0952  164.995             3.0    0.821
2           0.1530  169.996             4.0    0.598
3           0.4450  169.996             4.0    0.362
4           0.1580  128.961             4.0    0.593
...            ...      ...             ...      ...
62312       0.3530  100.024             4.0    0.504
62313       0.0813  110.041             4.0    0.524
62314       0.1370  122.038             4.0    0.669
62315       0.2850   74.993             4.0    0.439
62316       0.1170   89.975             4.0    0.837

                                               track_url  language
0      https://open.spotify.com/track/2r0ROhr7pRN4MXD...     Tamil
1      https://open.spotify.com/track/4I38e6Dg52a2o2a...     Tamil
2      https://open.spotify.com/track/59NoiRhnom3lTeR...     Tamil
3      https://open.spotify.com/track/5uUqRQd385pvLxC...     Tamil
4      https://open.spotify.com/track/1KaBRg2xgNeCljm...     Tamil
...                                                  ...       ...
62312  https://open.spotify.com/track/3eHDwMQYPEziy2D...     Tamil
62313  https://open.spotify.com/track/5hHtCqkNv5eo99O...     Tamil
62314  https://open.spotify.com/track/08foF9YHgKmIgOy...     Tamil
62315  https://open.spotify.com/track/2wLFbVlQGKJSd9l...     Tamil
62316  https://open.spotify.com/track/5OYxwYeFfumMTAo...     Tamil

[62317 rows x 22 columns]

In [5]:
import pandas as pd
cars = pd.read_json("sample2.json")
cars

                                                     shoppingList
groceries       [{'item': 'Apples', 'quantity': 3, 'unit': 'lb...
personalCare    [{'item': 'Toothpaste', 'quantity': 2, 'unit':...
householdItems  [{'item': 'Paper Towels', 'quantity': 4, 'unit...

In [9]:
import pandas as pd
boat = pd.read_excel("Project-Management-Sample-Data.xlsx")
boat

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
10,NaN,Product Dev,Quality Assurance,Fiona,2024-01-20 00:00:00,10,2024-01-30 00:00:00,0.78
11,NaN,Product Dev,User Interface Design,Gabriel,2024-02-04 00:00:00,25,2024-02-29 00:00:00,0
12,NaN,Customer Svc,Service Improvement,Hannah,2024-02-01 00:00:00,22,2024-02-23 00:00:00,1
13,NaN,Customer Svc,Ticket Resolution,Ian,2024-02-24 00:00:00,25,2024-03-20 00:00:00,1
14,NaN,Customer Svc,Customer Feedback,Julia,2024-03-21 00:00:00,30,2024-04-20 00:00:00,0
15,NaN,Financial,Budget Analysis,Kevin,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0.1
16,NaN,Financial,Financial Reporting,Mark,2024-02-13 00:00:00,21,2024-02-09 00:00:00,0.78
17,NaN,Financial,Investment Planning,Mark,2024-03-19 00:00:00,25,2024-04-13 00:00:00,1
18,NaN,Research,Market Trends Analysis,Nathan,2024-01-02 00:00:00,23,2024-01-25 00:00:00,0.5
19,NaN,Research,Data Collection,Olivia,2024-01-26 00:00:00,32,2024-02-27 00:00:00,0
20,NaN,Research,Research Paper Writing,Peter,2024-02-28 00:00:00,27,2024-03-26 00:00:00,0
21,NaN,Development,Software Development,Quinn,2024-01-02 00:00:00,36,2024-02-07 00:00:00,1
22,NaN,Development,Feature Enhancement,Rachel,2024-02-08 00:00:00,34,2024-03-13 00:00:00,0
23,NaN,Development,Code Review,Sam,2024-03-14 00:00:00,30,2024-04-13 00:00:00,0
24,NaN,Production,Manufacturing,Tim,2024-01-03 00:00:00,47,2024-02-19 00:00:00,0.3
25,NaN,Production,Quality Control,Ursula,2024-02-17 00:00:00,27,2024-03-15 00:00:00,0
26,NaN,Production,Packaging Design,Victor,2024-03-14 00:00:00,22,2024-04-05 00:00:00,0
27,NaN,Sales,Lead Generation,Wendy,2024-01-03 00:00:00,60,2024-03-03 00:00:00,0.7
28,NaN,Sales,Client Meetings,Xavier,2024-01-06 00:00:00,20,2024-01-26 00:00:00,0.78
29,NaN,Sales,Contract Negotiation,Yvette,2024-02-03 00:00:00,35,2024-03-09 00:00:00,0
30,NaN,Support,Technical Support,Zoe,2024-01-01 00:00:00,25,2024-01-26 00:00:00,1
31,NaN,Support,Bug Fixes,Aaron,2024-01-27 00:00:00,31,2024-02-27 00:00:00,1
32,NaN,Support,Software Updates,Bella,2024-03-02 00:00:00,22,2024-03-24 00:00:00,0
33,NaN,Operations,Process Optimization,Calvin,2024-01-03 00:00:00,30,2024-02-02 00:00:00,0.4
34,NaN,Operations,Inventory Management,Diane,2024-02-03 00:00:00,25,2024-02-28 00:00:00,0
35,NaN,Operations,Facility Maintenance,Edward,2024-02-29 00:00:00,20,2024-03-20 00:00:00,0
36,NaN,Consulting,Strategic Planning,Fiona,2024-01-02 00:00:00,35,2024-02-06 00:00:00,0.6
37,NaN,Consulting,Market Expansion,Gary,2024-02-02 00:00:00,32,2024-03-05 00:00:00,0
38,NaN,Consulting,Client Advisory,Helen,2024-03-06 00:00:00,25,2024-03-31 00:00:00,0
39,NaN,Training,Employee Training,Isaac,2024-01-04 00:00:00,27,2024-01-31 00:00:00,0.8
40,NaN,Training,Certification Programs,Jane,2024-01-28 00:00:00,30,2024-02-27 00:00:00,0
41,NaN,Training,Skill Development,Kyle,2024-02-28 00:00:00,22,2024-03-21 00:00:00,0
42,NaN,Events,Event Planning,Laura,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.3
43,NaN,Events,Conference Management,Mike,2024-02-03 00:00:00,20,2024-02-23 00:00:00,0
44,NaN,Events,Sponsorship Coordinatio,n Nancy,2024-02-24 00:00:00,35,2024-03-30 00:00:00,0
45,NaN,Logistics,Supply Chain Management,Oscar,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.5
46,NaN,Logistics,Transportation Planning,Patricia,2024-01-29 00:00:00,30,2024-02-28 00:00:00,1
47,NaN,Logistics,Inventory Optimization,Quentin,2024-03-29 00:00:00,20,2024-04-18 00:00:00,0
48,NaN,Engineering,Product Design,Rachel,2024-01-02 00:00:00,25,2024-01-27 00:00:00,0.2
49,NaN,Engineering,System Integration,Sam,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0
50,NaN,Engineering,Prototype Testing,Tom,2024-02-23 00:00:00,27,2024-03-21 00:00:00,0